name: Actions GitHub Workflow
on:
  #schedule:
    #- cron: "0 16 * * 0"
  workflow_call:
    inputs:
      reuse:
        required: false
        type: boolean
        default: false  
  workflow_dispatch:

jobs:
  jod_del:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:       
      - name: Delete workflow
        if: (inputs.reuse == false)
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          #retain_days: 1
          keep_minimum_runs: 0
          use_daily_retention: true